---

- name: Update - Clear Drush cache
  shell: "{{ aegir_drush }} @none cc drush"
  become: yes
  become_user: "{{ aegir_user }}"

- name: Update - Delete Drush cache
  file:
    state: absent
    path: "/var/aegir/.drush/cache/"

# TODO: On Ansible 2.3.x replace `shell: zip` with native Ansible task: `archive`
- name: Update - Backup Provision
  shell: zip -r {{ aegir_root }}/backup-.drush-$(date +'%Y_%m_%d-%H_%M_%S').zip /var/aegir/.drush/
  become: yes
  become_user: "{{ aegir_user }}"

- name: Update - Find Hostmaster path
  shell: "{{ aegir_drush }} @hm st | \\grep 'Drupal root' | \\grep -oh '/var/aegir/\\S*'"
  become: yes
  become_user: "{{ aegir_user }}"
  register: aegir_hostmaster_path

# TODO: On Ansible 2.3.x replace `shell: zip` with native Ansible task: `archive`
- name: Update - Backup Hostmaster
  shell: "zip -r {{ aegir_root }}/backup-hostmaster-$(date +'%Y_%m_%d-%H_%M_%S').zip {{ aegir_hostmaster_path.stdout }}"
  become: yes
  become_user: "{{ aegir_user }}"

- name: Update - Backup Hostmaster database
  shell: "{{ aegir_drush }} @hm sql-dump > {{ aegir_root }}/backup-hostmaster-db-$(date +'%Y_%m_%d-%H_%M_%S').sql"
  become: yes
  become_user: "{{ aegir_user }}"

# - name: Update - Update Provision
#   shell: "{{ aegir_drush }} --yes dl --destination={{ aegir_root }}/.drush provision-7.x-{{ aegir_version }}"
#   become: yes
#   become_user: "{{ aegir_user }}"

- name: Update - Checkout new Provision version
  git:
    repo: http://git.drupal.org/project/provision.git
    dest: "{{ aegir_root }}/.drush/provision"
    # depth: 1 # Speeds things up # It doesn't work on Ansible 2.2: https://github.com/ansible/ansible-modules-core/issues/5457
    version: "{{ aegir_core }}-{{ aegir_version }}"
    update: true
  become: yes
  become_user: "{{ aegir_user }}"

- name: Update - Clear Drush cache
  shell: "{{ aegir_drush }} @none cc drush"
  become: yes
  become_user: "{{ aegir_user }}"

- name: Update - Write Hostmaster makefile from template
  template:
    src: aegir.make.yml.j2
    dest: "{{ aegir_root }}/aegir.make.yml"
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"
    mode: 0644

- name: Update - Update Hostmaster
  shell: "{{ aegir_drush }} --yes @hostmaster hostmaster-migrate {{ aegir_frontend_url }} {{ aegir_root }}/hostmaster-7.x-{{ aegir_version }} --makefile='{{ aegir_root }}/aegir.make.yml'"
  become: yes
  become_user: "{{ aegir_user }}"

# TODO: hosting-queued refuse to start after update. Running the role `ansible-role-aegir-hosting-queued` fix the problem.
# - name: Restart Hosting Queued
#   systemd:
#       state: restarted
#       daemon_reload: yes
#       name: hosting-queued
#
# - name: Restart Hosting Queued
#   service:
#     name: hosting-queued
#     state: restarted
