---

- name: Check if Aegir is exist
  shell: "{{ aegir_drush }} sa | { \\grep '@hm' || true; }" # grep will return false and break the playbook, so we add always return true.
  become: yes
  become_user: "{{ aegir_user }}"
  register: check_aegir_exist
  changed_when: false

- name: Call the initial setup
  include: aegir-setup.yml
  when: check_aegir_exist.stdout == "" # If the `drush sa | grep '@hm'` doesn't find anything (empty string) then install Aegir.

- name: Check Aegir version
  command: \grep -oh "3.[0-9]*" /var/aegir/.drush/provision/aegir.make
  register: check_aegir_version
  changed_when: false
  when: check_aegir_exist.stdout == "@hm" # If the `drush sa | grep '@hm'` finds hostmaster then find the Aegir version.

- name: Update if version is greater than current
  include: aegir-update.yml
  when: check_aegir_version.stdout | default(100) | version_compare(aegir_version, '<') # If Aegir does not exist check_aegir_version will be NULL, so we initialize it with a big number to avoid run the update. If hostmaster version is smaller then update Aegir.
