#- name: Register {{ aegir_root }}/.drush/provision
#  stat: path="{{ aegir_root }}/.drush/provision"
#  register: provision_folder

- name: Clone Provision
  git:
    repo: http://git.drupal.org/project/provision.git
    dest: "{{ aegir_root }}/.drush/provision"
    depth: 1 # Speeds things up
    version: "{{ aegir_provision_version }}"
    update: "{{ aegir_provision_update }}"
  become: yes
  become_user: "{{ aegir_user }}"
  #when: provision_folder.stat.isdir is not defined

- name: Clear Drush cache for Provision extension
  shell: drush @none cc drush
  become: yes
  become_user: "{{ aegir_user }}"
  environment:
    PATH: "{{ aegir_drush_path }}:{{ ansible_env.PATH }}"
  changed_when: false # This will never report 'changed' status. But it will report 'ok', 'unreachable' or 'failed'

- name: Write Hostmaster makefile from template
  copy:
    dest: "{{ aegir_root }}/aegir.make"
    content: "{{ aegir_makefile_contents }}"
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"

- name: Build Hostmaster platform
  shell: "drush make {{ aegir_root }}/aegir.make {{ aegir_root }}/hostmaster-{{ aegir_platform_version }} --working-copy --no-gitinfofile"
  args:
    creates: "{{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/"
  become: yes
  become_user: "{{ aegir_user }}"
  environment:
    PATH: "{{ aegir_drush_path }}:{{ ansible_env.PATH }}"

- name: Create aegir db user
  mysql_user:
    name: aegir
    host: "%"
    password: "{{ aegir_db_password }}"
    priv: "*.*:ALL,GRANT"
    state: present

- name: Install Aegir front-end
  shell: "drush @none --yes hostmaster-install --debug --working-copy --aegir_db_host={{ aegir_db_host | default('localhost') }} --aegir_db_user={{ aegir_db_user }} --aegir_db_pass={{ aegir_db_password }} --aegir_version={{ aegir_platform_version }} {{ aegir_frontend_url }} --strict=0 --root={{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/ --client_email={{ aegir_client_email }}"
  args:
    creates: "{{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/sites/{{ aegir_frontend_url }}/"
  become: yes
  become_user: "{{ aegir_user }}"
  environment:
    PATH: "{{ aegir_drush_path }}:{{ ansible_env.PATH }}"
  register: aegir_install

- file:
    src: /var/aegir/config/apache.conf
    dest: /etc/httpd/conf.d/aegir.conf
    state: link
    owner: root
    group: root
    mode: 0777

- name: Verify Aegir front-end
  shell: drush @hm cc drush && drush @hm hosting-task @hostmaster verify --force
  become: yes
  become_user: "{{ aegir_user }}"
  environment:
    PATH: "{{ aegir_drush_path }}:{{ ansible_env.PATH }}"
  changed_when: false # This will never report 'changed' status. But it will report 'ok', 'unreachable' or 'failed'

- name: restart httpd
  service: name=httpd state=restarted
  when: aegir_install.changed
